export const UploadPurposes = {
  PROFILE_IMAGE: 'PROFILE_IMAGE',
  // Worker
  WORKER_DOCUMENT: 'WORKER_DOCUMENT',
  WORKER_COVER_IMAGE: 'WORKER_COVER_IMAGE',
  WORKER_PROFILE_IMAGE: 'WORKER_PROFILE_IMAGE',
  // Category
  CATEGORY_ICON: 'CATEGORY_ICON',
  CATEGORY_IMAGE: 'CATEGORY_IMAGE',

  HOME_HOW_IT_WORKS_IMAGE: 'HOME_HOW_IT_WORKS_IMAGE',
  HOME_WHY_CHOOSE_IMAGE: 'HOME_WHY_CHOOSE_IMAGE',
  HOME_TESTIMONIAL_IMAGE: 'HOME_TESTIMONIAL_IMAGE',
  HOME_BANNER_IMAGE: 'HOME_BANNER_IMAGE',
  SERVICE_EVIDENCE: 'SERVICE_EVIDENCE',
  REVIEW_EVIDENCE: 'REVIEW_EVIDENCE',
  DISPUTE_EVIDENCE: 'DISPUTE_EVIDENCE',
  CHAT_IMAGE: 'CHAT_IMAGE',
  CHAT_VIDEO: 'CHAT_VIDEO',
  CHAT_AUDIO: 'CHAT_AUDIO',
} as const;

export type UploadPurpose = (typeof UploadPurposes)[keyof typeof UploadPurposes];
